# dependabot analyzing npm dependencies
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "content-downloader"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
