export const github_projects_user = 'patrickfav';

export const github_projects = [
    {repo: 'bcrypt', branch: 'master'},
    {repo: 'Dali', branch: 'master'},
    {repo: 'under-the-hood', branch: 'master'},
    {repo: 'density-converter', branch: 'master'},
    {repo: 'uber-apk-signer', branch: 'master'},
    {repo: 'armadillo', branch: 'master'},
    {repo: 'BlurTestAndroid', branch: 'master'},
    {repo: 'uber-adb-tools', branch: 'master'},
    {repo: 'bytes-java', branch: 'master'},
    {repo: 'indoor-positioning', branch: 'master'},
    {repo: 'hkdf', branch: 'master'},
    {repo: 'slf4j-timber', branch: 'master'},
    {repo: 'id-mask', branch: 'master'},
    {repo: 'dice', branch: 'master'},
    {repo: 'singlestep-kdf', branch: 'master'},
    {repo: 'bkdf', branch: 'master'},
    {repo: 'rocketchat-exporter', branch: 'master'},
    {repo: 'docker-minipaint', branch: 'main'},
    {repo: 'planb-android', branch: 'master'},
    {repo: 'checkstyle-config', branch: 'master'},
    {repo: 'bankathon16-inso', branch: 'master'},
    {repo: 'website-dr-sel', branch: 'master'},
    {repo: 'website-favre', branch: 'main'},
]
