name: Build Site and Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  pull_request: {}
  schedule:
    - cron: '42 2 * * *' # run 2:42 am every day

env:
  FIREBASE_PROJECT_ID: favre-base-project
  NODE_VERSION: 18.14.0
  WORKING_DIR: './content-downloader'

jobs:
  build_and_deploy:
    name: Build Site and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code und Submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Prepare Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: NPM Install Content Downloader
        run: npm ci && npm link
        working-directory: ${{ env.WORKING_DIR }}
      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ env.WORKING_DIR }}
      - name: Run NPM Audit
        run: npm audit signatures && npm audit --audit-level=high
        working-directory: ${{ env.WORKING_DIR }}
      - name: Update Content
        uses: nick-fields/retry@v2
        if: github.event_name == 'schedule'
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 3
          command: ${{ env.WORKING_DIR }}/bin/hugo-content-downloader
      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.109.0'
          extended: true
      - name: Build Site with Hugo
        env:
          HUGOxPARAMSxGITxLAST_COMMITxHASH: ${{ vars.GITHUB_SHA }}
          HUGOxPARAMSxGITxLAST_BUILDxID: ${{ vars.GITHUB_RUN_ID }}
          HUGOxPARAMSxGITxLAST_BUILDxNUMBER: ${{ vars.GITHUB_RUN_NUMBER }}
        run: |
          hugo version && \
          hugo config && \
          hugo --verbose --printPathWarnings --minify

      - name: Deploy to Firebase Hosting
        id: firebase-deploy-prod
        if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAVRE_BASE_PROJECT }}'
          channelId: live
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
      - name: Deploy to Firebase Hosting (dev preview channel)
        id: firebase-deploy-preview
        if: github.event_name == 'pull_request'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FAVRE_BASE_PROJECT }}'
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          expires: 7d
